version: "3.8"

services:
  n8n-caddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "5678:5678"
    networks:
      - n8n_network
    environment:
      TZ: Asia/Tokyo
      SSL_EMAIL: example@example.com
      DOMAIN_NAME: localhost
      GENERIC_TIMEZONE: Asia/Tokyo
      N8N_DEFAULT_LOCALE: ja
      N8N_USER_MANAGEMENT_DISABLED: "false"
      N8N_SMTP_HOST: mailhog
      N8N_SMTP_PORT: 1025
      N8N_SMTP_SENDER: noreply@example.com
      N8N_SMTP_SSL: "false"
    volumes:
      - ./Procfile:/app/Procfile

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
    networks:
      - n8n_network
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

networks:
  n8n_network:

volumes:
  maildir: {}